Draft: Initial PR
bentoml/BentoInfinity pull request #1
Opened 2024-07-05 07:07 UTC by michaelfeil

2024-07-06 06:04 UTC, michaelfeil commented
@ssheng

2024-07-08 12:54 UTC, larme requested changes
Overall very good PR, just left some minor suggestions. Also could you give every endpoint's api function some meaningful default inputs so user can try the service without providing their own inputs?

2024-07-08 12:54 UTC, larme commented on bentofile.yaml
> +    - git
Why we need git here? Does installing `infinity_emb` require git?

2024-07-08 12:54 UTC, larme commented on requirements.txt
> +infinity_emb[all]>=0.0.50
As an example project, we should lock `infinity_emb`'s version to 0.0.50

2024-07-08 12:54 UTC, larme commented on service.py
> +        self.array = AsyncEngineArray.from_args(
I think `self.array` -> `self.engine_array` would be a better name.

2024-07-08 12:54 UTC, larme commented on service.py
> +                    batch_size=4,
why is `batch_size` set to 4?

2024-07-08 12:54 UTC, larme commented on service.py
> +    async def embeddings(self, input: list[str], model: str) -> t.Dict:
Maybe we should give`input` a more meaningful name (e.g. like `sentences`?)

2024-07-08 18:57 UTC, michaelfeil commented on service.py
> +    async def embeddings(self, input: list[str], model: str) -> t.Dict:
Agreed, but this way generates an API client compatible to https://platform.openai.com/docs/guides/embeddings - therefore lets keep it like this.

2024-07-08 18:57 UTC, michaelfeil commented on bentofile.yaml
> +    - git
removed the docker section.

2024-07-09 02:56 UTC, larme approved these changes
LGTM for now

2024-07-09 08:38 UTC, merged